Add custom contact info fields to puppet profile
mautrix/whatsapp pull request #605
Opened 2023-04-04 22:37 UTC by vurpo

Some of those fields are hardcoded, but on the other hand it feels pretty justified?

2023-04-05 10:06 UTC, tulir reviewed
I think these were already fixed in the doc

2023-04-05 10:06 UTC, tulir commented on puppet.go
> +			"com.beeper.bridge.remoteId":    puppet.JID.String(),
```suggestion
			"com.beeper.bridge.remote_id":    puppet.JID.String(),
```

2023-04-05 10:06 UTC, tulir commented on puppet.go
> +			"com.beeper.bridge.isBot":       false,
```suggestion
			"com.beeper.bridge.is_bridge_bot": false,
			"com.beeper.bridge.is_bot":       false,
```

2023-04-05 16:52 UTC, sumnerevans requested changes

2023-04-05 16:52 UTC, sumnerevans commented on main.go
> +	if br.Config.Homeserver.Software == bridgeconfig.SoftwareHungry {
Can we move this gate further down? Maybe check right in `puppet.UpdateContactInfo` so that we don't have to remember to gate every call

2023-04-06 23:19 UTC, sumnerevans requested changes
I don't see the logic for setting the bridge bot's contact info either here or in mautrix-go. Here's the change that I made in mautrix-python to do that: https://github.com/mautrix/python/blob/754ec520f3e6b13ec22624ce4c8aa84e87c03d1f/mautrix/bridge/matrix.py#L275-L284

2023-04-07 14:27 UTC, sumnerevans approved these changes

2023-04-10 15:38 UTC, tulir approved these changes

2023-04-10 15:39 UTC, merged